CREATE TABLE contract (
    id SERIAL PRIMARY KEY,
    doc_num VARCHAR(255),
    doc_date DATE,
    period DATE,
    adress VARCHAR(255),
    start_date DATE,
    end_date DATE,
    start_time VARCHAR,
    end_time VARCHAR,
    discount FLOAT,
    discount_money DECIMAL,
    summa DECIMAL,
    payment BOOLEAN DEFAULT FALSE,
    organization_id INT REFERENCES organization(id),
    account_number_id INT REFERENCES account_number(id),
    all_worker_number INTEGER,
    all_task_time  FLOAT,
    remaining_balance DECIMAL DEFAULT 0,
    user_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    isdeleted BOOLEAN DEFAULT FALSE
);

