CREATE TABLE shablon (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    shablon_name VARCHAR(200),
    title VARCHAR,
    main_section TEXT[],
    section_1 TEXT[],
    section_1_title VARCHAR,
    section_2 TEXT[],
    section_2_title VARCHAR,
    section_3 TEXT[],
    section_3_title VARCHAR,
    section_4 TEXT[],
    section_4_title VARCHAR,
    section_5 TEXT[],
    section_5_title VARCHAR,
    section_6 TEXT[],
    section_6_title VARCHAR,
    section_7 TEXT[],
    section_7_title VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    isdeleted BOOLEAN DEFAULT FALSE
);