CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    fio VARCHAR,
    login VARCHAR(100),
    password VARCHAR(100),
    image VARCHAR(10000),
    region_id INTEGER REFERENCES regions(id) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    isdeleted BOOLEAN DEFAULT FALSE
);